name: StrictDonateMoney
version: '${project.version}'
main: play.strictmc.ru.strictdonatemoney.StrictDonateMoney
api-version: '1.16'
authors: [ vstep, parimek, StrictMC ]
description: Плагин просто добавляет донатную валюту. Точнее заглушка поверх плагина PlayerPoints
website: https://strictmc.ru/
depend: [PlayerPoints]